# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-18 10:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20160809_1957'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('detail', models.TextField()),
                ('start_month', models.DateField(default=datetime.datetime(2016, 8, 18, 10, 31, 50, 19612, tzinfo=utc))),
                ('end_date', models.DateField(default=datetime.datetime(2016, 8, 18, 10, 31, 50, 20121, tzinfo=utc))),
            ],
        ),
        migrations.RemoveField(
            model_name='resume',
            name='user',
        ),
        migrations.AddField(
            model_name='resume',
            name='Nationality',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume',
            name='XIIth_board_mark',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume',
            name='XIIth_class_board',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume',
            name='XIIth_school_name',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume',
            name='Xth_board_mark',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume',
            name='Xth_class_board',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume',
            name='Xth_school_name',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume',
            name='acad_details',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume',
            name='branch',
            field=models.CharField(choices=[('CSE', 'CSE'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('MECH', 'MECH'), ('ICE', 'ICE'), ('CHEM', 'CHEM'), ('PROD', 'PROD'), ('CIVIL', 'CIVIL'), ('META', 'META')], default=0, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume',
            name='cgpa',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2016, 8, 18, 10, 31, 50, 18612, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='resume',
            name='email',
            field=models.EmailField(default=0, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume',
            name='father_name',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default=0, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume',
            name='languages',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume',
            name='operating_systems',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume',
            name='other_details',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume',
            name='packages',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume',
            name='position_of_resp',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume',
            name='programming_languages',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume',
            name='sports_details',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resume',
            name='address',
            field=models.TextField(),
        ),
        migrations.AddField(
            model_name='project',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Resume'),
        ),
    ]
