# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-18 10:38
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0004_auto_20160818_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='user',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2016, 8, 18, 10, 38, 41, 734377, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_month',
            field=models.DateField(default=datetime.datetime(2016, 8, 18, 10, 38, 41, 734377, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='resume',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2016, 8, 18, 10, 38, 41, 732373, tzinfo=utc)),
        ),
    ]
