# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-18 10:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20160818_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2016, 8, 18, 10, 38, 57, 272721, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_month',
            field=models.DateField(default=datetime.datetime(2016, 8, 18, 10, 38, 57, 272721, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='resume',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2016, 8, 18, 10, 38, 57, 271720, tzinfo=utc)),
        ),
    ]
