# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-18 14:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20160818_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='start_month',
        ),
        migrations.AddField(
            model_name='project',
            name='start_date',
            field=models.DateField(blank=True, default=datetime.datetime(2016, 8, 18, 14, 51, 49, 985188, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='detail',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.datetime(2016, 8, 18, 14, 51, 49, 985188, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2016, 8, 18, 14, 51, 49, 984186, tzinfo=utc)),
        ),
    ]
