# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-09 09:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20160820_0807'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gpa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sem_no', models.CharField(choices=[('I', 'Semester I'), ('II', 'Semester II'), ('III', 'Semester III'), ('IV', 'Semester IV'), ('V', 'Semester V'), ('VI', 'Semester VI'), ('VII', 'Semester VII'), ('VIII', 'Semester VIII')], max_length=20)),
                ('gpa', models.CharField(max_length=5)),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.datetime(2016, 10, 9, 9, 52, 9, 767510, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(blank=True, default=datetime.datetime(2016, 10, 9, 9, 52, 9, 767481, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2016, 10, 9, 9, 52, 9, 766306, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='gpa',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Resume'),
        ),
    ]
