# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-11 06:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_auto_20161011_0642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.datetime(2016, 10, 11, 6, 52, 3, 13603, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(blank=True, default=datetime.datetime(2016, 10, 11, 6, 52, 3, 13574, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2016, 10, 11, 6, 52, 3, 12514, tzinfo=utc)),
        ),
    ]
